version: 0.0
os: linux
files:
  - source: ./coffee-tracker-backend
    destination: /ubuntu/coffee-tracker
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 3000
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 3000
      runas: ubuntu
